apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-agency-app
  labels:
    app: travel-agency-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-agency-app
  template:
    metadata:
      labels:
        app: travel-agency-app
    spec:

      volumes:
        - name: travel-agency-app-storage
          persistentVolumeClaim:
            claimName: travel-agency-app-storage-claim
        - name: travel-agency-app-mysql
          persistentVolumeClaim:
            claimName: travel-agency-app-mysql-claim

      # secret gitlab token
      imagePullSecrets:
        - name: gitlab-token-auth

      # initContainer
      initContainers:
        - name: copy-storage
          image: git.webased.net:5050/webased/travelagencyapp:latest
          command: ['sh', '-c', 'cp -a /usr/src/travel-agency-app/storage/* /data/travel-agency-app/storage']
          volumeMounts:
            - name: travel-agency-app-storage
              mountPath: /data/travel-agency-app/storage

      containers:
        # AppContainer
        - name: app
          image: git.webased.net:5050/webased/travelagencyapp:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: travel-agency-app-storage
              mountPath: /usr/src/travel-agency-app/storage

        # MysqlContainer
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: travel-agency-app-mysql
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_DATABASE
              value: "travel_agency_app"
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: SERVICE_TAGS
              value: "dev"
            - name: SERVICE_NAME
              value: "mysql"
