version: '3.7'

services:
  app:
    image: travel-agency
    restart: always
    ports:
      - '8001:80'
    depends_on:
      - db
    volumes:
      - .:/usr/src/travel-agency
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3304:3306'
    volumes:
      - ./docker/db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: travel_agency
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
