apiVersion: v1
kind: Service
metadata:
  name: travel-agency-app
spec:
  selector:
    app: travel-agency-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30006
